version: '3.7'

services:
  # DB
  cadmus-graph-pgsql:
    image: postgres
    container_name: cadmus-graph-pgsql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    networks:
      - cadmus-graph-network

  ## API
  cadmus-graph-api:
    image: vedph2020/cadmus-graph-api:0.0.1
    container_name: cadmus-graph-api
    ports:
      - 5153:80
    depends_on:
      - cadmus-graph-index
    environment:
      - CONNECTIONSTRINGS__TEMPLATE=Server=cadmus-graph-pgsql;port=5432;Database={0};User Id=postgres;Password=postgres;Include Error Detail=True
      - DATABASENAME=cadmus-graph
      - SEED__INDEXDELAY=25
    networks:
      - cadmus-graph-network

networks:
  cadmus-graph-network:
    driver: bridge
